name: crc32
version: 0.1.2
description: A cyclic redundancy check calculator for Dart written in pure Dart.
author: Kai Sellgren <kaisellgren@gmail.com>
homepage: http://github.com/kaisellgren/CRC32
dependencies:
  unittest: any

